FROM openjdk:17-oracle
LABEL authors="QUANG"
EXPOSE 8080
COPY target/management_file-0.0.1-SNAPSHOT.jar management_file-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "management_file-0.0.1-SNAPSHOT.jar"]